### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ES6')

### ISSUE THREAD

**Issue by fatihorucu** [drudge/mongoose-findorcreate#35]
`
const findOrCreate = require('mongoose-findorcreate');
const userSchema = new mongoose.Schema({
    email: String,
    password: String,
})

userSchema.plugin(passportLocalMongoose);
userSchema.plugin(findOrCreate);

const User = mongoose.model("User", userSchema)

passport.use(new GoogleStrategy({
    clientID: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    callbackURL: "http://localhost:3000/auth/google/secrets",
    userProfileURL: "https://www.googleapis.com/oauth2/v3/userinfo"
},
    function (accessToken, refreshToken, profile, cb) {
        console.log(profile);

        User.findOrCreate({ googleId: profile.id }, function (err, user) {
            return cb(err, user);
        });
    }
));`

Here is my code but I keep getting the error below.

> TypeError: Cannot read properties of undefined (reading 'ES6')
    at Function.findOrCreate (/home/fatih/Web Development/Secrets/node_modules/mongoose-findorcreate/index.js:11:37)
    at Strategy._verify (/home/fatih/Web Development/Secrets/app.js:65:14)
    at /home/fatih/Web Development/Secrets/node_modules/passport-oauth2/lib/strategy.js:205:24
    at /home/fatih/Web Development/Secrets/node_modules/passport-google-oauth20/lib/strategy.js:122:5
    at passBackControl (/home/fatih/Web Development/Secrets/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/home/fatih/Web Development/Secrets/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by firely7** [comment]
This might be beacuse you are using mongoose 7.0; Read on the issues in the section below:
https://github.com/drudge/mongoose-findorcreate/issues/34#issue-1595011074

In stackoverflow there is a comment on how to create the functions that you need:
https://stackoverflow.com/questions/20431049/what-is-function-user-findorcreate-doing-and-when-is-it-called-in-passport
